### ISSUE TITLE
pg_yregress: initdb: could not find suitable text search configuration for locale "UTF-8"

### ISSUE THREAD

**Issue by ccleve** [omnigres/omnigres#287]
I get `initdb: could not find suitable text search configuration for locale "UTF-8"` when I run pg_yregress against the demo test.yml.

I installed pg_yregress via homebrew.

**Comment by yrashk** [comment]
Can you show the output of the `locale` command?

**Comment by ccleve** [comment]
But I'm not sure where this output is coming from. Here's pg_config:

***@***.*** pg_yregress % pg_config
BINDIR = ***@***.***/14.8_2/bin
DOCDIR = ***@***.***/14.8_2/share/doc
HTMLDIR = ***@***.***/14.8_2/share/doc
INCLUDEDIR = ***@***.***
PKGINCLUDEDIR = ***@***.***
...

Was this installed by pg_yregress, or is it left over from some other
install of mine?

**Comment by ccleve** [comment]
Yes, pg_yregress continues to work.

I'm not sure how to set LC_ALL. A bit of quick googling did not turn up an
immediate answer.

**Comment by yrashk** [comment]
This should do it

```
export LC_ALL=en_US.UTF-8
```

**Comment by ccleve** [comment]
Yes, that fixes the problem.

**Comment by yrashk** [comment]
I am closing this issue for now. If you have any idea on how this can be further improved, please feel free to suggest a contribution or open a new issue or a discussion.

Thank you!
