### ISSUE TITLE
Problem: omni_containers depends on libcurl & yyjson

### ISSUE THREAD

**Issue by yrashk** [omnigres/omnigres#319]
These dependencies complicate our build unnecessarily, and we miss the benefits of using omni_httpc. Maintaining the C code as it is is becoming burdensome.

Proposed solution: rewrite most of omni_containers in PL/pgSQL

Instead of libcurl & yyjson we can use omni_httpc and native JSON support in Postgres.

Likely, some functionality will remain implemented in C.

In particular, the processing of streams to text has to unpack frames with network byte order headers, for which one would likely need to expose `pg_ntoh32` as a stored procedure (see https://github.com/omnigres/omnigres/blob/master/extensions/omni_containers/omni_containers.c#L409-L428)

However, the rest of the logic can be migrated away.

---

**Bounty size: $250**

[Read more about bounties](https://github.com/omnigres/omnigres/wiki/Bounties)

**Comment by rmodpur** [comment]
@yrashk I would like to take this up
