### ISSUE TITLE
Problem: omni_python is undocumented

### ISSUE THREAD

**Issue by yrashk** [omnigres/omnigres#320]
This is a severe roadblock in its adoption.

Proposed solution: write usage documentation outlining the workflow

It should have a good amount of good, meaningful examples and feature Flask integration.

You can gather how to use it in these places:

* https://www.loom.com/share/b4701cbc77e941919cd5dbff7b15465e
* https://github.com/omnigres/omnigres/tree/master/extensions/omni_python/tests
* https://github.com/omnigres/omnigres/blob/master/extensions/omni_schema/tests/omni_python.yml
* [Discord](https://discord.omnigr.es)

---

**Bounty size: $250**

[Read more about bounties](https://github.com/omnigres/omnigres/wiki/Bounties)

**Comment by Akshat-Jain** [comment]
@yrashk I'd like to claim this one. Can you assign it to me?
