### ISSUE TITLE
Problem: omni_containers is undocumented

### ISSUE THREAD

**Issue by yrashk** [omnigres/omnigres#321]
This is a severe roadblock in its adoption.

Proposed solution: write usage documentation outlining its usage

[Tests](https://github.com/omnigres/omnigres/tree/master/extensions/omni_containers/tests) is a good start for understanding how to use omni_containers.

Just to let you know, if #319 will be worked on, it may affect this issue. It'd be great to handle this issue before #319, though.

---

**Bounty size: $100**

[Read more about bounties](https://github.com/omnigres/omnigres/wiki/Bounties)

**Comment by rmodpur** [comment]
@yrashk I would like to work on this
