### ISSUE TITLE
Json serialisation of a sum types

### ISSUE THREAD

**Issue by rosssaunders** [omnigres/omnigres#358]
Hi,

I'm playing around with omni_types.sum_type to see how it serialises to Json out of the box using to_json().

I've got the following basic example:

```drop type if exists example_as_type cascade;

select omni_types.sum_type('oneormany', 'text', 'text[]');
create type example_as_type as
(
    id int,
    name oneormany
);

select to_json(row(1, 'example message'::text::oneormany)::example);
```

I'm expecting the following string returned:

```
{
   "id": 1,
   "name":"example message"
}
```

however the code returns the full postgres string version.

```
{
   "id": 1,
   "name": "text(example message)"
}
```

I've taken a look at http_json to override the to_json formatting, however that only appears to be for tables and not types. 

Am I doing anything incorrectly or is this a current limitation of the omni_types.sum_type at the moment?

Thanks,

Ross

**Comment by yrashk** [comment]
That is currently a limitation of sum types, we can't quite dispatch to a correct to_json[b] implementation. 

You'd have to type cast the sum type to a specific member type to get the correct implementation to dispatch to.

It might be possible to override to_json functions for every new sum type and dispatch there. Something to consider. A question that arises here is whether we need to dispatch other common functions to member types?

Overall, definitely an interesting aspect we haven't solved just yet.

**Comment by rosssaunders** [comment]
Understood... thanks for the fast response! I'll look into casting in my code to the underlying type instead.
