### ISSUE TITLE
Problem with omni_aws when uploading files to DigitalOcean s3 alternative.

### ISSUE THREAD

**Issue by my-might** [omnigres/omnigres#376]
We deployed the project to DigitalOcean and used its objects storage. When we're trying to process put_object 
`SELECT * FROM
        omni_aws.aws_execute(access_key_id => _access_key_id, secret_access_key => _secret_access_key,
                             request => omni_aws.s3_put_object(bucket := _bucket, path => _path,
                                                               payload => _payload, content_type => _content_type, region => _region),
                             endpoint_url => _endpoint)`
we're getting an error
`{
    "error": "P0001",
    "message": "403<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>SignatureDoesNotMatch</Code><Message></Message><RequestId>tx00000bafd0cc58ab18e94-00655b869a-a0f4fea-sfo2b</RequestId><HostId>a0f4fea-sfo2b-sfo2-zg02</HostId></Error>"
}`
We've tried to use specific DigitalOcean region - sfo2. Then we've tried to use aws-compatible - us-east-1. The result was the same.

The same code worked when we used Minio.

**Comment by yrashk** [comment]
How does the endpoint_uri look like?

**Comment by my-might** [comment]
https://sfo2.digitaloceanspaces.com

**Comment by yrashk** [comment]
Should be solved in #379
