### ISSUE TITLE
Problem: omni_aws DigitalOcean S3 support

### ISSUE THREAD

**Issue by yrashk** [omnigres/omnigres#391]
Seemingly everything (with the exception signed) URLs doesn't work with the `digitalocean_s3_endpoint()` backend, returning a signature mismatch error.

---

**Bounty size: $100**

[Read more about bounties](https://github.com/omnigres/omnigres/wiki/Bounties)

**Comment by rmodpur** [comment]
From https://docs.digitalocean.com/reference/api/spaces-api/#list-a-buckets-contents

> The version 2 list type is not currently supported.

**Comment by rmodpur** [comment]
Some observations:
1. create bucket api => able to create buckets through extension if payload is empty, digitalocean is rejecting bucket create requests with payload (even with official aws-sdk )
2. put object api => able to put objects through official aws-sdk but is failing with `400Bad Request` for extension

On debug logging official aws sdk i found digitalocean spaces api is responding with HTTP/2.0 response for HTTP/1.1 requests, so i tried switching to http2 for extension but it is failing with generic 'I/O error'

**Comment by yrashk** [comment]
Addressed in #397
