### ISSUE TITLE
Problem: omni_vfs backend support is still limited

### ISSUE THREAD

**Issue by yrashk** [omnigres/omnigres#402]
Currently, omni_vfs only has only one backend: `local_fs`. This is very limiting as this is not as practical on the server.

Proposed solution: implement a `table_fs` that will provide the same API for table-backed filesystems.

Different designs can be considered, but it is important to ensure the performance of finding/listing files under a directory (recursively) as well as direct lookup.

I've had a (not a correctly implemented) attempt before: https://github.com/yrashk/omnigres/commit/b159f5631d84946af574c3b4faa5100b1b9001f2. Feel free to consult with it.

---

**Bounty size: $250**

[Read more about bounties](https://github.com/omnigres/omnigres/wiki/Bounties)

**Comment by rmodpur** [comment]
Interested
