### ISSUE TITLE
Problem: `locale` setting of database is dependent on environment

### ISSUE THREAD

**Issue by rmodpur** [omnigres/omnigres#416]
[omni_vfs table_fs](https://github.com/omnigres/omnigres/pull/403) tests failed due to inconsistent sort ordering of text between my machine and CI runners.

The reason turned out to be different `LC_COLLATE`(responsible for String sort order) was different `en_US.UTF-8` (on my machine) and `C.UTF-8` (on CI runners) because

from [postgres documentation](https://www.postgresql.org/docs/15/locale.html)

> Locale support is automatically initialized when a database cluster is created using initdb. initdb will initialize the database cluster with the locale setting of its execution environment by default
When we speak of inheriting the locale from the execution environment, this means the following on most operating systems: For a given locale category, say the collation, the following environment variables are consulted in this order until one is found to be set: LC_ALL, LC_COLLATE (or the variable corresponding to the respective category), LANG. If none of these environment variables are set then the locale defaults to C

We are not explicitly setting any locale in our 
[initdb command](https://github.com/omnigres/omnigres/blob/master/cmake/PostgreSQLExtension.cmake#L485)

from [postgres documentation](https://www.postgresql.org/docs/15/locale.html)

> If you want to use a different locale (or you are not sure which locale your system is set to), you can instruct initdb exactly which locale to use by specifying the --locale option

**Comment by rmodpur** [comment]
Although a bit unrelated, we might as well set a default encoding in `initdb` command

**Comment by yrashk** [comment]
This should be a relatively trivial change to `pg_yregress`!

**Comment by rmodpur** [comment]
How about using 
```bash
--no-locale           equivalent to --locale=C
```
and encoding as `utf8` ?

**Comment by yrashk** [comment]
We can set that as a default unless overridden in the `instance`/`instances` entry (with the `locale:` and `encoding` keys), what do you think?

**Comment by rmodpur** [comment]
sounds good, i will raise a PR
