### ISSUE TITLE
Problem: dealing with HTTP API redirects

### ISSUE THREAD

**Issue by yrashk** [omnigres/omnigres#444]
Some APIs (or websites) redirect elsewhere before serving any content. Implementing a logic that requires making another request in this case is bothersome, especially if it needs to be done in many places.

Proposed solution: research and implement adding (default?) `follow_redirect` option.

---

**Bounty size: $100**

[Read more about bounties](https://github.com/omnigres/omnigres/wiki/Bounties)

**Comment by ThisIsRahmat** [comment]
@yrashk hi, can I be assigned this issue?

**Comment by UkuLoskit** [comment]
A small survey of popular tools and librarires (biased towards what I have used):
**curl (cli)** - disabled by default, follows 30 redirects if enabled 
**requests (Python)** - enabled by default, 30 by default
**HttpClient (Go)** enabled by default, 10 redirects
**HttpClient (Java 11)** - enabled by default
**Guzzle(PHP)** - enabled by default, 5 redirects

Safety considerations:
https://datatracker.ietf.org/doc/html/rfc7231#section-4.2.1

So, for this implementation it should be decided if this should be enabled by default.
How many redirects to follow? Should the count be configurable?
Probably makes sense to follow the RFC in terms of safety. Although even then there are differences between these which verb to follow.

**Comment by UkuLoskit** [comment]
From my reading of the h2o source, it seems to me that redirect handling is only implemented for the server code, but not client code. I might be mistaken though.
