### ISSUE TITLE
Problem: omni_manifest fails to update extension version

### ISSUE THREAD

**Issue by rmodpur** [omnigres/omnigres#475]
Bug reproduction:

1. checkout omnigres commit `2c7e737` then cmake configure and build
2. s3 sync extension upgrade scripts to a local directory and just copy `omni_aws--2c7e737--e135aa7.sql` and `omni_aws--e135aa7.control` to `build/pg-share/extension`
3. run `make psql_omni_aws` and create `omni_aws` and `omni_manifest` extension
4. run the following sql query to upgrade just `omni_aws`

```
select *
from
    omni_manifest.install(
            'omni_aws=e135aa7#omni_httpc=*,pgcrypto=*,omni_xml=*,omni_web=*'::text::omni_manifest.artifact[])
;
```

postgres backend crashes with `No matching control file found for name   version 2c7e737` message

I have applied the following diff for better diagnostic message, empty name seems to be coming from `unload_extension`

```
diff --git a/extensions/omni_ext/omni_ext.c b/extensions/omni_ext/omni_ext.c
index fb9775f..445b5de 100644
--- a/extensions/omni_ext/omni_ext.c
+++ b/extensions/omni_ext/omni_ext.c
@@ -427,7 +427,7 @@ char *load_extension(char *name, char *version) {
     load_control_file(search.unversioned_match, (void *)&config);
     result = "";
   } else {
-    ereport(ERROR, errmsg("No matching control file found"));
+    ereport(ERROR, errmsg("No matching control file found for name %s version %s", name, version));
   }
 
   return result;
@@ -473,7 +473,7 @@ bool unload_extension(char *name, char *version) {
     load_control_file(search.unversioned_match, (void *)&config);
     result = true;
   } else {
-    ereport(ERROR, errmsg("No matching control file found"));
+    ereport(ERROR, errmsg("No matching control file found for name %s version %s", name, version));
   }
   // TODO: free allocated resources (shmem & workers)? or should this be a responsibility
   // of the extension to ensure this is done exactly how they need it?
```

**Comment by yrashk** [comment]
I've seen a similar case of an empty name on a spurious unload. It meant some condition was happening that made `omni_ext` think it needed to unload the extension, but it didn't. #462 was somewhere in that area.

Looking at `omni_manifest.install_plan` for this artifact might illuminate the cause.

P.S. I am [working on `omni`](#473) to replace `omni_ext`, and it won't suffer from its problems.

**Comment by rmodpur** [comment]
The name is not empty, it's just a space `' '`

**Comment by rmodpur** [comment]
`omni_manifest` expects it install function to be called in an explicit transaction, it worked fine when run after a begin statement

**Comment by yrashk** [comment]
I think that must be an interplay with `omni_ext`'s [handling of extension alteration](https://github.com/omnigres/omnigres/blob/master/extensions/omni_ext/hooks.c#L84), especially (I suspect) in cases when the version

**Comment by rmodpur** [comment]
Found the fix
```diff
diff --git a/extensions/omni_ext/hooks.c b/extensions/omni_ext/hooks.c
index cc0b198..5411523 100644
--- a/extensions/omni_ext/hooks.c
+++ b/extensions/omni_ext/hooks.c
@@ -138,7 +138,7 @@ void omni_ext_process_utility_hook(PlannedStmt *pstmt, const char *queryString,
 
         char *extversion = pstrdup(altered_extversion);
         ExtensionReference *drop = palloc(sizeof(ExtensionReference));
-        drop->name = stmt->extname;
+        drop->name = pstrdup(stmt->extname);
         drop->version = extversion;
         extensions_to_drop = lappend(extensions_to_drop, drop);
```

**Comment by rmodpur** [comment]
I noticed `omni_manifest` is only able to handle extension dependencies one level below
for eg.
```sql
select *
from
    omni_manifest.install(
            'omni_aws=2c7e737#omni_httpc=2c7e737,pgcrypto=*,omni_xml=2c7e737,omni_web=2c7e737'::text::omni_manifest.artifact[])
```

fails with `required extension "omni_http" is not installed`
Is omission of `cascade` in `execute format('create extension %s version %L', (rec.req).name, rec.target_version)` intentional ?
