### ISSUE TITLE
Problem: overriding `postgres` symbols

### ISSUE THREAD

**Issue by yrashk** [omnigres/omnigres#543]
As discovered during a debugging session on #537, there's a chance for a subtle problem when a Postgres symbol is overridden by an extension. Specifically, if a symbol is defined in the extension and `postgres`, the linker may pick `postgres`'s version of the symbol over the one in the extension

On macOS/clang it seems to compile and link correctly (as we'd expect it) but on Linux/gcc it didn't.

Proposed solution: run an intersection of `nm -g --defined-only` (or `nm -g -U` on macOS, it seems)
on both the compiled extension and `postgres`.

If there's any intersection, error out.

---

**Bounty size: $100**

[Read more about bounties](https://github.com/omnigres/omnigres/wiki/Bounties)

**Comment by UkuLoskit** [comment]
Hey, @yrashk ! Could you assign it to me? Seems straight-forwad enough.

**Comment by yrashk** [comment]
Here you go!
