### ISSUE TITLE
Problem: Cmake is crashing while building OpenSSL on Rocky 9

### ISSUE THREAD

**Issue by JoshInnis** [omnigres/omnigres#703]
Hi Yurii,

I pulled down Omnigres master onto a machine with Rocky Linux 9 and ran the first build command `cmake -S . -B build` . I receive the follow errors:

```
sh/financial_database/omnigres/build/_deps/openssl-build/lib64/engines-3\"" -DMODULESDIR="\"/home/josh/financial_database/omnigres/build/_deps/openssl-build/lib64/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF ssl/quic/libssl-shlib-quic_thread_assist.d.tmp -MT ssl/quic/libssl-shlib-quic_thread_assist.o -c -o ssl/quic/libssl-shlib-quic_thread_assist.o ssl/quic/quic_thread_assist.c
during RTL pass: ira
In file included from ssl/quic/quic_method.c:12:
ssl/quic/quic_method.c: In function 'OSSL_QUIC_client_method':
ssl/quic/quic_local.h:336:9: internal compiler error: Segmentation fault
  336 |         }
      |         ^
ssl/quic/quic_method.c:14:1: note: in expansion of macro 'IMPLEMENT_quic_meth_func'
   14 | IMPLEMENT_quic_meth_func(OSSL_QUIC_ANY_VERSION,
      | ^~~~~~~~~~~~~~~~~~~~~~~~
```

Shortened for brevity

```
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.rockylinux.org/> for instructions.
```

Shortened for brevity

```
The bug is not reproducible, so it is likely a hardware or OS problem.
make[1]: *** [Makefile:20830: ssl/quic/libssl-shlib-quic_method.o] Error 1
make[1]: *** Waiting for unfinished jobs....
./util/libcrypto.num: No new symbols added
make[1]: Leaving directory '/home/josh/financial_database/omnigres/build/_deps/openssl-src'
make: *** [Makefile:3600: build_sw] Error 2
CMake Error at cmake/OpenSSL.cmake:65 (message):
  Failed to build OpenSSL
Call Stack (most recent call first):
  cmake/FindPostgreSQL.cmake:54 (include)
  pg_yregress/CMakeLists.txt:11 (find_package)
```

On my machine I can however, reproduce this error. Do you see anything that might fix this before I submit an OS bug report?

**Comment by JoshInnis** [comment]
Note: If I run the build command again, it forcibly reboots my computer

**Comment by yrashk** [comment]
Josh, wow, that's quite something! Thank you for reporting this.

I can't think of why this would happen off the top of my head. As a mitigation, I'd suggest passing --DOPENSSL_CONFIGURED=1 to use locally installed `openssl-devel`

Happy ro continue exploring this issue! Let me know if you'd like more help here or on Discodd.

**Comment by JoshInnis** [comment]
for reference: https://bugs.rockylinux.org/view.php?id=8449

**Comment by JoshInnis** [comment]
@yrashk Could you check that OS ticket I linked? They closed it before I could respond. Is Omnigres using a custom OpenSSL version? 

It seems you are both recommending the same thing though, so I will try that. However, if I run the build command twice my computer forcibly restarts. This seems like something that shouldn't just be solved by a workaround...

**Comment by yrashk** [comment]
@JoshInnis, no, it's vanilla OpenSSL that was downloaded and built by the build system. Even if it _was_ custom, I doubt the compiler should crash or reboot the computer!

**Comment by yrashk** [comment]
Closing the issue. Feel free to re-open if necessary!
